version: "3.8"
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: gitcoin-stewards
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - "./:/usr/share/nginx/html"
